apiVersion: v2
name: nmaas
description: GÃ‰ANT Network Management as a Service Helm chart for Kubernetes
version: 1.2.7
appVersion: 1.5.4
keywords:
- Network Management
- Cloud Deployment
- Automated Configuration
maintainers:
- email: nmaas-dev@lists.geant.org
  name: nmaas-platform
  url: https://docs.nmaas.eu
dependencies:
- name: postgresql
  version: 10.16.2
  repository: https://artifactory.software.geant.org/artifactory/nmaas-helm-mirror
  condition: postgresql.install
